### PR TITLE
WPSC_Duplicate_Product Class

### PR DESCRIPTION
**Pull request by benhuson**
@JustinSainton After doing all the recent updates to the product duplication functionality, I thought It might be better suited to component-ize it into a class.

No-body should really be using the those functions but I've make it back-compatible with the existing functions which we can deprecate if we commit this - happy to add in the deprecated function calls.

What do you think?

### CODE REVIEW

**Comment by JustinSainton** [comment]
Love the idea!  Looks really good so far! Do you want to properly deprecate the old procedural functions in another PR, or just make that commit to this branch?  (Also, a few super minor scrutinizer issues).

**Comment by benhuson** [comment]
I'll build on this PR and check those issues :)

**Comment by benhuson** [comment]
Should I move the deprecated functions to https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-core/wpsc-deprecated.php ?

**Comment by JustinSainton** [comment]
Yep!

**Comment by benhuson** [comment]
@JustinSainton Scrutinizer seemed to error in my last push so I can't check results. Are you able to re-trigger the check?

**Comment by benhuson** [comment]
@JustinSainton 

Scrutinizer came up with a few minor issues saying "Blank line found after control structure". Are we not supposed to a line break after an if statement if it makes it more readable?

Also it's suggesting for docs to "Consider making the return type a bit more specific; maybe use integer." when it can actual return `int` OR `WP_Error`. Is that an issue?

**Comment by JustinSainton** [comment]
I think we can fix the control structure spacing (not sure where that standard comes from, but it seems to be inline with core).  The integer docs issue - I'd ignore that.

**Pull request merged**
