### PR TITLE
Bug fixes for the PayPal Gateways

### PR DESCRIPTION
**Pull request by omarabid**
This fixes

- Remove Expresscheckout and Digital goods icon popups

- Add a Spinner for PayPal Pro Hosted
Issue: Once i click Purchase on checkout the gateways list is hidden and so is the button so the page looks like a big white space until the paypal "response" comes back with the card input data..maybe a spinner or something so the user knows to hold on until it loads ?

https://dl.dropboxusercontent.com/u/16683640/Screenshots/2015-04-30_2307.png

### CODE REVIEW

**Comment by JustinSainton** [comment]
@omarabid Can you copy the descriptions of the issues here? That's a private board.

**Comment by omarabid** [comment]
Only one had a description by @misulicus, adding it.

**Comment by JustinSainton** [comment]
@omarabid Still adding it?

**Comment by omarabid** [comment]
@JustinSainton I added it (edited) on the PR description?

**Comment by JustinSainton** [comment]
Ah, don't mind me, I haven't had enough coffee.

**Pull request merged**
