### PR TITLE
Fix object caching in wpsc_get_meta().

### PR DESCRIPTION
**Pull request by benhuson**
First attempt at fixing the object caning in wpsc_get_meta() for issue #1894.

I'm not sure what the point of compacting the non-existant 'meta_value' is then filtering it, when it get's overwritten by the query shortly after?

```
$meta_tuple = compact( 'object_type', 'object_id', 'meta_key', 'meta_value', 'type' );
$meta_tuple = apply_filters( 'wpsc_get_meta', $meta_tuple );
extract( $meta_tuple, EXTR_OVERWRITE );
```

Anyone have any ideas about that?

### CODE REVIEW

**Comment by JustinSainton** [comment]
Yeah, I'd say the `meta_value` there isn't really doing too much.  Probably safe to remove.

**Comment by benhuson** [comment]
@JustinSainton As the meta value is part of the array that get's filtered by 'wpsc_get_meta', maybe I should just leave in as a blank/null value as perhaps add a deprecated notice if the value is changed after the filter?

Not sure who might be using the 'wpsc_get_meta' filter and for what but at least that would notify them that trying to change the meta value in the array does't do anything. Or is that just being too over-careful, and we should just remove?

**Comment by JustinSainton** [comment]
@benhuson That _might_ be a bit overly careful.  Only because it never actually worked, and searching Github and Google shows no code out in the wild actually attempting to use the filter. I think we can afford to be a tad presumptuous here with code that never really worked.

**Comment by benhuson** [comment]
@JustinSainton Agreed.

**Comment by JustinSainton** [comment]
Cool, so I'm happy to merge here.

I'd like to see what WP does for core object cache API unit testing.  We should definitely test this API.

**Comment by benhuson** [comment]
@JustinSainton Agreed.

It also seems a little odd filtering $type in that array too as a few lines previously:

```
$object_type = $type;
```

...then $type is not referred to again. So I guess that can go too leaving only `object_type`, `object_id`, `meta_key` as filterable by the 'wpsc_get_meta' filter.

Also, just thought, if using `extract()` should we be checking the keys of the `$meta_tuple` first? What if someone returned a custom $wpdb in that filter?

**Comment by JustinSainton** [comment]
That works for me - and if you want to get rid of the extract usage completely, I'd be delighted :)

**Comment by benhuson** [comment]
Will have a play...

I'm not entirely sure why the filter's there at all? I'm guessing you could filter the keys and object id for some sort of back compatibility? I would have just assumed the filter would be for filtering the returned data not filtering the keys to get the data.

Oh well, maybe best leave that in case it breaks something ;)

**Comment by JustinSainton** [comment]
Sounds good to me :)

**Pull request merged**
