### PR TITLE
Remove unused(?) code.

### PR DESCRIPTION
**Pull request by leewillis77**
So - I'm starting to look through the current scrutinizer results. 

This result is due to a use of print_r():

https://scrutinizer-ci.com/g/wp-e-commerce/WP-e-Commerce/inspections/567c6915-c284-4887-8724-35c82c86b714/issues/files/wpsc-admin/ajax-and-init.php?status=existing&selectedAuthors%5B0%5D=leewillis77%40gmail.com&orderField=path&order=asc

Looking into it I don't think this segment of code is used, so I'm removing it. Here's what I've checked for:
* Any references to the wpsc_product_page_order option (None)
* Any other references to 'product-page-order' (Only referenced in admin-legacy.js in a handler that's attached to element with a class of meta-box-sortables - removed in this PR)
* Looked for any other occurrences of meta-box-sortables to see if we're creating any such elements - only referenced in a CSS file - removed in this PR. 

So - this PR should silence the original Scrutinizer error as well as remove some unneeded PHP, JS and CSS. Anyone point out anything I've missed - or know that this code is required?

### CODE REVIEW

**Comment by JustinSainton** [comment]
Sweet!  Yeah, IIRC, that's all actually from 3.7.  Very old stuff.  Should be fine to cut out.

**Comment by leewillis77** [comment]
Would you prefer to add more commits to this PR, or raise separate ones for each item. Next on my list is some shockers in wpsc-admin/display-debug.page.php - can we just remove that - or do people use it?

**Comment by JustinSainton** [comment]
I'm quite sure that page is never, ever, ever used.  It hasn't been referenced in core in ages....and anyone accessing it directly is doing really, really weird things.  I feel _fairly_ confident no one would be accessing that, or require/includeing it in a way that that would cause fatal errors if we remove it.  

And yes, more commits in this PR is fine.

**Comment by leewillis77** [comment]
Hey @JustinSainton - that set of commits above could use a second opinion - are you happy for us to rip all the debug out - there's similar cruft in other gateways which I can trim out if we decide it doesn't belong there.

**Comment by leewillis77** [comment]
Hi Justin, 

So - that's a random set of changes across a whole bunch of areas. Most should be pretty safe to merge. The contentious ones, or ones that might need further review are:
* 4267193
* a2cb831 (Looks sane, but I'd be happier if I could work out a nice way of testing - Jeff may have an opinion on this?)

**Comment by JustinSainton** [comment]
4267193 is fine, as I'd like to see Chronopay out of core as soon as possible anyway.

a2cb831 almost looks sane, except for the `$_POST['$meta']`, which should likely be `$_POST['meta']`

**Comment by leewillis77** [comment]
Scrutinizer is confusing me, pretty sure none of the 132 "new" issues are introduced here.

**Comment by JustinSainton** [comment]
@leewillis77 Right, Scrutinizer is a little silly sometimes.  It knows neither reason nor rhyme with how it identifies issues.  If you're ever concerned, you can sort by "Last Found".  And in this case, you're all good.  I'll go ahead and merge.

**Pull request merged**
