### PR TITLE
Tidying up wpsc_get_meta()

### PR DESCRIPTION
**Pull request by benhuson**
Tidying up wpsc_get_meta(), extending on PR #1908 for issue #1894

Get's rid of extract()

### CODE REVIEW

**Comment by JustinSainton** [comment]
I assume the actual changes to fix #1894 will come in a separate PR?

**Comment by benhuson** [comment]
Yep. Just added this as a separate PR to build on the other wpsc_get_meta() changes already merged.

**Comment by JustinSainton** [comment]
:+1: So this is good to merge?

**Comment by benhuson** [comment]
Yep, merge away :smiley:

Separate PR on it's way shortly to deal with the multiple request issues for you to review.
(merge this first though)

**Pull request merged**
