### PR TITLE
New Feature - predefined sales periods for Sales Log dropdown

### PR DESCRIPTION
**Pull request by 1bigidea**
Includes pre-defined typical sales periods into the Sales Log Filter. Includes three new filters so that the output of the pre-defined periods can be modified as well as allowing extension of new periods. Uses the core WP_Date_Query to create the sql needed.

### CODE REVIEW

**Comment by 1bigidea** [comment]
I am sure that I ducked this up by doing a merge instead of a rebase. I might need a quick how-to un-duck it up.

**Comment by JeffPyeBrook** [comment]
@1bigidea  

Hi Tom,  what I usually do to get a clean branch for a PR (pull request) is a process like the following:

1) fetch upstream, this gets you the current repository
2) checkout upstream/master, this should get you a copy of master in a detached head
3) checkout -b into a new branch for the PR, i like to name them something like "pr-some-cool-feature" or pr-issue#-fix-bad-bug-like-this" so i can distinguish development branches from PR branches
4) cherry-pick the commits from the development branch into the new branch created for the PR
5) If there are many commits that have no value as individual actions sometimes I will do a rebase -i to squash them down
6) Do the PR

Hope that helps, 
Jeff

**Comment by 1bigidea** [comment]
Thanks Jeff - that is useful. I know Justin is going to yell at me for ducking up his commit history.



Every successful WordPress project starts with...
One Big Idea

(360) 746-2101                         transom@1bigidea.com
(815) 642-0258 efax 
gChat: transom@1bigidea.com    SKYPE: tomransom
Twitter: wp_site_manager                     www.linkedin.com/in/onebigidea


On April 26, 2015 at 11:25:48 AM, Jeff @ Pye Brook (notifications@github.com) wrote:

@1bigidea

Hi Tom, what I usually do to get a clean branch for a PR (pull request) is a process like the following:

1) fetch upstream, this gets you the current repository
2) checkout upstream/master, this should get you a copy of master in a detached head
3) checkout -b into a new branch for the PR, i like to name them something like "pr-some-cool-feature" or pr-issue#-fix-bad-bug-like-this" so i can distinguish development branches from PR branches
4) cherry-pick the commits from the development branch into the new branch created for the PR
5) If there are many commits that have no value as individual actions sometimes I will do a rebase -i to squash them down
6) Do the PR

Hope that helps,
Jeff

**Comment by 1bigidea** [comment]
I am going to try this again brb

**Pull request closed without merging**
