### PR TITLE
Provide purchase log bulk actions for statuses added via filter.

### LINKED ISSUE #1723: Use global statuses for order bulk actions
Suggestion: Order statuses are coded into the global $wpsc_purchlog_statuses (which is filterable), but then these aren't used for the bulk actions. Instead, the bulk actions are [hard-coded here](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-admin/includes/purchase-log-list-table-class.php#L564).

Seems like using the purchase log statuses to create the actions would make this more flexible & make it easier to add custom statuses.

### PR DESCRIPTION
**Pull request by leewillis77**
This generates bulk actions for non-standard purchase log statuses. This fixes #1723.

Some thoughts on this though:
* Should we document the new filter in the function docblock - or inline a la WP core?
* Any idea why the hardcoded restriction on $current_action was there - am I breaking anything by removing it?
* Should *all* the actions be generated from the global status array?

### CODE REVIEW

**Comment by JustinSainton** [comment]
Looks really good so far, @leewillis77!  

* Yes, absolutely document the filter a la WP core.  We'll have a significant effort towards better documentation on all fronts over the course of this year - this would be a great first filter to document :)
* No real effort was made in the commit message for a76e95fefa71592a251497b0e811a37da1888b07 to indicate why that was limited.  Best guess: was not done with the thought of compatibility with extending custom purchases statues.  I don't think we'll break anything by removing it.
* I think so.  What are your thoughts?

Also - what are your thoughts on also tackling #1525 as a part of this?  I think it would make sense, personally. 

Lastly - let me know if you think it'd be overkill to have a simple WPSC_Purchase_Status object.  Wondering if that may not be beneficial for the minor gain in having a singleton vs. a global, having core methods for registering/deregistering statuses, being a bit more sane to test, generally.  Totally doesn't need to be a part of this PR - just thinking out loud :)

**Comment by leewillis77** [comment]
So - the attached should generate the bulk actions fully dynamically, instead of keeping the hard-coded list of "standard" actions. It also adds docs for the filter (That I removed, and re-added due to a WP core WTF). 

It also generates the view links dynamically based on the wpsc_purchlog_statuses global. Opinions sought on this since it may be an i18n regression. If we feel that it is, then I think the suggestion @benhuson made in #1525 is probably the way to go - I can update if needs be.

**Comment by JustinSainton** [comment]
Yeah, I'd agree, I think that @benhuson's suggestion in #1525 would be a good thing to implement here as well - you concur?

**Comment by benhuson** [comment]
I agree, obviously ;)

**Comment by leewillis77** [comment]
So - I think this is ready for review now. Particular bits to pay attention to:
* The attempt at catering for cases where the status doesn't provide an _nx_noop'd view label (E.g. Custom statuses already in existence)
* Do we want to filter the view links like we're doing for the bulk actions while we're here?

**Comment by JustinSainton** [comment]
View links, yes please - that's the crux of #1525.

**Comment by leewillis77** [comment]
#1525 was about generating view links for statuses added via the filter. This PR supports that - custom statuses will get view links. You can provide custom translations as part of the status array when you add your status, or a default will be provided for back compat with people already using the filter.

My question was about whether we wanted an additional filter on the view links array?

**Comment by JustinSainton** [comment]
Ahh...hmm...trying to think of a use case where you'd want different output on the view links array than you'd want on the rest of the output affected by the main filter on the statuses.  Can't really think of any...can you?

**Comment by leewillis77** [comment]
I can't think of any sane ones, so let's go without a filter for now. We can always review if someone comes up with a use case.

**Comment by JustinSainton** [comment]
Lovely, will merge as soon as Scrutinizer re-runs.

**Pull request merged**
