### PR TITLE
Coupon API

### PR DESCRIPTION
**Pull request by benhuson**
For issue #1624

Introduces a new WPSC_Coupon class and uses throughout core.

Will need some thorough testing...

### CODE REVIEW

**Comment by JustinSainton** [comment]
This all looks really, really good.  Would love to see some unit tests as well, especially since we're replacing old `$coupon` variables in some `do_action` calls with the new data structure...would be great to have test coverage there to confirm that we're maintaining back compat.

Great, great work, @benhuson.

**Comment by benhuson** [comment]
I need to swat up on Unit Tests a bit. Will refer to the existing WPEC ones and see if I can get to grips with it and get it set up locally.

**Comment by benhuson** [comment]
@JustinSainton My first time delving properly into unit testing - a good excuse, I've been putting it of for a while...

Please can you cast your eyes over this:
https://github.com/benhuson/WP-e-Commerce/commit/813bd556de901332c69a948499d111a1d6fdfcc7

I've just written some tests for the base functionality to try to get to grips with what is required.

I needed to create a set_current_user_as_administrator() function in order to pass the admin checks, and then create data before testing it.

Am I sort of along the right lines....?

**Comment by JustinSainton** [comment]
@benhuson Definitely along the right lines!  Looking really, really good. 

One test I'd run is to do a sort of faux mock of the current data model [returned here](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-admin/display-coupon-edit.php#L8), and confirm that the get_data() method returns the same.

**Comment by JustinSainton** [comment]
Going to go ahead and merge.  Will add the unit test later.

**Comment by instinct** [comment]
Could this almost be enough to warrant a minor point release?

**Comment by benhuson** [comment]
I've put together some more unit tests, and they actually picked up an issue with the delete functionality - am starting to see the benefit of them already ;)

Deletes from DB fine, but doesn't clear data in the current object in case you try to reuse it. Just writing a patch for that now and will submit a PR with that and unit tests in the morning.

**Comment by JustinSainton** [comment]
Awesome!  Thanks so much for the work, @benhuson, this will be a huge improvement!

**Pull request merged**
