### PR TITLE
Swapping out Chosen for Select2

### PR DESCRIPTION
**Pull request by curtismchale**
Totally just a placeholder for the PR at this point.

We moved out the chosen files and swapped in the Select2 files which means, it's all brokeded.

Github Issue: https://github.com/wp-e-commerce/WP-e-Commerce/issues/1263
Theme Engine ticket placeholder: https://github.com/wp-e-commerce/WP-e-Commerce/issues/848

- [x] move out chosen files and in select2
- [x] change over the multi-select js to select2
- [ ] make sure that ajax update of the widget refreshes the select
- [x] make sure select all works reliably
- [x] make sure select none works reliably
- [ ] style the select to match WP backend and expected widget styles
- [ ] make sure there isn't other usages outside of the widgets that Curtis missed on first pass

### CODE REVIEW

**Comment by JustinSainton** [comment]
:+1:

**Comment by JustinSainton** [comment]
@curtismchale Heyo!  Got everything basically functional.  The main area I think you were seeing this function was in the category drill down widget.  We're holding off on that specific widget until 4.1 - see #1834 - but I made the Product Categories widget work with it.  

There is also a Select2 input on the Presentation Settings page, under the category filter setting. 

Both of those sections definitely need some styling work, but other than that, we're looking pretty solid.

**Comment by curtismchale** [comment]
@JustinSainton take a look at those styles

**Comment by JustinSainton** [comment]
I definitely read your comment to the tune of https://youtu.be/_ZMUeBJOWhA?t=57

**Comment by curtismchale** [comment]
oh my...not sure if I'm happy or sad about that

**Comment by JustinSainton** [comment]
couple things - [some whitespace/standards issues in the css](https://make.wordpress.org/core/handbook/coding-standards/css/#structure).

also, it no longer merges clean. can you rebase/fix the merge?

**Pull request merged**
